name: "flow"

on:
  pull_request:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  flow-test:
    name: Flow
    permissions:
      checks: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [16]
    runs-on: ${{ matrix.os }}
    env:
      TEST_ENV: ${{ matrix.test_env || 'production' }}
    steps:
      - uses: actions/checkout@v3
      - run: cp install/package.json package.json
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - run: npm run flow check --all
