name: "flow"

on:
  pull_request:

jobs:
  flow-test:
    name: Flow
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [16]
    runs-on: ${{ matrix.os }}
    env:
      TEST_ENV: ${{ matrix.test_env || 'production' }}
    steps:
      - run: npm run flow check --all
